version: '3.7'

services:

  back:
    container_name: film-back
    image: film
    user: "1000:1001"
    working_dir: /app
    build: ./deploy
    ports: ["127.0.0.1:8000:8000"]
    volumes:
      - ./back:/app
      - ./media:/media
      - ./logs:/logs
      - ./deploy/gunicorn.py:/gunicorn.py
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  front:
    container_name: film-front
    image: node:18
    working_dir: /app
    volumes:
      - ./front:/app
    command: sleep 30d