version: '3.7'

services:

  db:
    ports: ["127.0.0.1:5432:5432"]

  front:
    ports: ["127.0.0.1:3000:3000"]

  back:
    ports: ["127.0.0.1:5000:5000"]
    command: uvicorn main:server --reload --host 0.0.0.0 --port 5000

  # nginx:
  #   container_name: sphere_fast-nginx
  #   image: nginx:stable
  #   depends_on: [back, front]
  #   user: "${UID}:${GID}"
  #   # ports: ["127.0.0.1:3000:3000"]
  #   volumes:
  #     - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./deploy/nginx.${RUN_MODE}.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./logs/nginx_access.log:/var/log/nginx/access.log
